export const site = {
  name: 'Bringel Advocacia',
  short: 'Bringel Advocacia',
  monogram: 'BA',
  theme: 'clay',
  kicker: 'ADVOCACIA PREVIDENCIÁRIA · PARAUAPEBAS',
  title: 'Direitos previdenciários com clareza e cuidado.',
  intro: 'Orientação especializada em Direito Previdenciário para quem busca segurança nas decisões sobre aposentadoria e benefícios junto ao INSS.',
  quote: 'Entender o INSS é o primeiro passo para garantir aquilo que é seu por direito.',
  about: 'Em Parauapebas, a Bringel Advocacia oferece atendimento especializado em Direito Previdenciário, acompanhando cada etapa do processo perante o INSS com atenção e transparência.',
  address: 'Rua 6, 18 — Parauapebas · PA',
  phone: '[INSERIR TELEFONE]',
  whatsapp: '',
  map: 'https://www.google.com/maps/search/?api=1&query=-6.0641869,-49.9096432',
  instagram: '',
  image: '/hero.jpg',
  areas: [
    ['Aposentadoria', 'Análise do tempo de contribuição e orientação sobre o melhor caminho para aposentar.', 'shield'],
    ['Benefícios por Incapacidade', 'Orientação em auxílios e benefícios relacionados à saúde e ao trabalho.', 'heart'],
    ['Revisão de Benefícios', 'Análise de benefícios já concedidos para verificar direitos não considerados.', 'refresh'],
    ['Planejamento Previdenciário', 'Leitura do histórico contributivo para decisões mais conscientes sobre o futuro.', 'trend'],
  ] as [string, string, string][],
  values: [
    'Atendimento especializado em Direito Previdenciário',
    'Análise individualizada de cada histórico contributivo',
    'Acompanhamento próximo em cada etapa junto ao INSS',
  ],
  faq: [
    ['Como funciona o primeiro contato com o escritório?', 'O atendimento começa com uma breve explicação da situação previdenciária, para organizar a análise do caso com mais detalhes.'],
    ['Quais documentos costumam ser necessários?', 'Documentos pessoais, CNIS, carteira de trabalho e comunicações do INSS. Cada caso pode exigir documentos específicos.'],
    ['O escritório atende apenas aposentadoria?', 'Não. Além de aposentadorias, a atuação inclui benefícios por incapacidade, planejamento previdenciário e revisão de benefícios.'],
    ['É possível revisar um benefício já concedido?', 'Em determinadas situações, sim. A análise do histórico contributivo pode indicar se há espaço para revisão.'],
  ] as [string, string][],
};
